version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: moe
      MONGO_INITDB_ROOT_PASSWORD: 123456789


  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: moe
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456789

volumes:
  mongodb: {}